encrypt:
  key: vprxxl5blpycu3kt8602
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
  profiles:
    active: git,security
  security:
    user:
      name: user
      password: password