server:
  port: 8888
---
spring:
  cloud:
    stream:
      defaultBinder: rabbit
  config:
    activate:
      on-profile: cloud-bus-rabbit
---
spring:
  cloud:
    stream:
      defaultBinder: kafka
  config:
    activate:
      on-profile: cloud-bus-kafka
