spring:
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT key, value from PROPERTIES where application=? and profile=? and label=?
  datasource:
    url: jdbc:postgresql://postgres:5432/cloud_config
    username: root
    password: password
  profiles:
    active: jdbc
