version: '2'

# Docker Compose example for testing a remote git repo

services:
  # Configured through environment variables
  config-server-env:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/spring-cloud-samples/config-repo
    volumes:
      - ./config:/config

  # Configured through mounted config volume
  config-server-dir:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    volumes:
      - ./config:/config

  # Configured through system properties
  config-server-props:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    environment:
      JAVA_OPTS: -Dspring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo

  # Configured through command line arguments
  config-server-args:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    command: --spring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
    ports:
      - "8888"
