version: '2'

# Docker Compose example for testing security with a remote git repo

services:
  # Configured through environment variables
  config-server-env:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    environment:
      ENCRYPT_KEY: vprxxl5blpycu3kt8602
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/spring-cloud-samples/config-repo
      SPRING_PROFILES_ACTIVE: git,security
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: password
    volumes:
      - ./config:/config

  # Configured through mounted config volume
  config-server-dir:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    volumes:
      - ./config:/config

  # Configured through system properties
  config-server-props:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    environment:
      JAVA_OPTS: >
        -Dencrypt.key=vprxxl5blpycu3kt8602
        -Dspring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
        -Dspring.profiles.active=git,security
        -Dspring_security.user.name=user
        -Dspring.security.user.password=password

  # Configured through command line arguments
  config-server-args:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    ports:
      - "8888"
    command:
      - --encrypt.key=vprxxl5blpycu3kt8602
      - --spring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
      - --spring.profiles.active=git,security
      - --spring_security.user.name=user
      - --spring.security.user.password=password
