version: '3.8'

# Docker Compose example for testing AWS S3

networks:
  aws:

services:
  # Configured through environment variables
  config-server-env:
    depends_on:
      - localstack
    container_name: config-server-env
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - aws
    ports:
      - "8881:8888"
    environment:
      SPRING_PROFILES_ACTIVE: awss3
      SPRING_CLOUD_CONFIG_SERVER_AWSS3_ENDPOINT: localhost.localstack.cloud:4566
      SPRING_CLOUD_CONFIG_SERVER_AWSS3_REGION: us-east-1
      SPRING_CLOUD_CONFIG_SERVER_AWSS3_BUCKET: sample-bucket

  # Configured through mounted config file
  config-server-dir:
    container_name: config-server-dir
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - aws
    ports:
      - "8882:8888"
    volumes:
      - ./application.yml:/config/application.yml

  # Configured through system properties
  config-server-props:
    container_name: config-server-props
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - aws
    ports:
      - "8883:8888"
    environment:
      JAVA_OPTS: >
        -Dspring.profiles.active=awss3
        -Dspring.cloud.config.server.awss3.endpoint=localhost.localstack.cloud:4566
        -Dspring.cloud.config.server.awss3.region=us-east-1
        -Dspring.cloud.config.server.awss3.bucket=sample-bucket


  # Configured through command line arguments
  config-server-args:
    container_name: config-server-args
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
        - aws
    ports:
        - "8884:8888"
    command:
        - --spring.profiles.active=awss3
        - --spring.cloud.config.server.awss3.endpoint=localhost.localstack.cloud:4566
        - --spring.cloud.config.server.awss3.region=us-east-1
        - --spring.cloud.config.server.awss3.bucket=sample-bucket

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    networks:
      aws:
        aliases:
          - localhost.localstack.cloud
          - sample-bucket.localhost.localstack.cloud
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: s3
      DEBUG: 1
    volumes:
      - ./config:/data/config
      - ./populate-s3.sh:/data/populate-s3.sh
