version: '3.8'

# Docker Compose example for testing Spring Cloud Bus Kafka

services:
  config-server-env:
    depends_on:
      - rabbitmq
    container_name: config-server-env
    image: hyness/spring-cloud-config-server
    ports:
      - "8881:8888"
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - SPRING_PROFILES_ACTIVE=cloud-bus-rabbit
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/spring-cloud-samples/config-repo
      - SPRING_RABBITMQ_HOST=rabbitmq
  config-server-dir:
    depends_on:
      - rabbitmq
    container_name: config-server-dir
    image: hyness/spring-cloud-config-server
    ports:
      - "8882:8888"
    volumes:
      - ./config:/config
  config-server-props:
    depends_on:
      - rabbitmq
    container_name: config-server-props
    image: hyness/spring-cloud-config-server
    ports:
      - "8883:8888"
    environment:
      JAVA_OPTS: -Dmanagement.endpoints.web.exposure.include=* -Dspring.profiles.active=cloud-bus-rabbit -Dspring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo -Dspring.rabbitmq.host=rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"