name: Build and deploy to registry

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      registry:
        description: Registry to deploy artifacts (docker.io, ghcr.io)
        required: true

env:
  REGISTRY: docker.io

jobs:
  build-vars:
    name: Create build variables
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ inputs.registry || steps.build-vars.outputs.registry }}
    steps:
      - id: build-vars
        name: Create build variables
        run: echo "registry=$REGISTRY" >> $GITHUB_OUTPUT

  cloud-config-versions:
    name: Find build and latest versions of cloud config
    uses: ./.github/workflows/cloud-config-versions.yml

  build-and-deploy-to-registry:
    name: Create OCI images and deploy to ${{ inputs.registry }}
    uses: ./.github/workflows/release.yml
    needs:
      - build-vars
      - cloud-config-versions
    strategy:
      matrix:
        jvmType: [jre, jdk]
        jvmVersion: [17, 21]
    with:
      build-version: ${{ needs.cloud-config-versions.outputs.build }}
      latest-version: ${{ needs.cloud-config-versions.outputs.latest }}
      jvm-version: ${{ matrix.jvmVersion }}
      jvm-type: ${{ matrix.jvmType }}
      registry: ${{ needs.build-vars.outputs.registry }}
    secrets: inherit

  update-docker-hub-description:
    name: Update Docker Hub README
    needs:
      - build-vars
      - build-and-deploy-to-registry
    if: needs.build-vars.outputs.registry == 'docker.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: hyness/spring-cloud-config-server
