name: dockerhub readme

on:
  workflow_run:
    workflows: ['dockerhub deploy']
    branches: [main]
    types:
      - completed

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    name: Push verified image to dockerhub

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Sync Readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          readme: "./README.md"
