name: Deploy artifacts to Dockerhub

on:
  workflow_run:
    workflows: ['CI']
    branches: [main, '[2-9].[0-9]']
    types:
      - completed

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le

jobs:
  create-variables:
    if: github.event.workflow_run.conclusion == 'success'
    name: Create build variables
    runs-on: ubuntu-latest
    outputs:
      cloud-config-version: ${{ steps.create-variables-output.outputs.cloud-config-version }}
      cloud-config-version-short: ${{ steps.create-variables-output.outputs.cloud-config-version-short }}
      short-sha: ${{ steps.create-variables-output.outputs.short-sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Create semver
        run: |
          echo "SEMVER=$(./gradlew dependencyInsight --dependency org.springframework.cloud:spring-cloud-config-server | grep 'org.springframework.cloud:spring-cloud-config-server:' | tail -1 | cut -d ':' -f 3-)" >> $GITHUB_ENV
      - name: Create outputs
        id: create-variables-output
        run: |
          echo "::set-output name=cloud-config-version::$SEMVER"
          echo "::set-output name=cloud-config-version-short::`echo $SEMVER | cut -d. -f1,2`"
          echo "::set-output name=short-sha::`echo $GITHUB_SHA | cut -c1-8`"

  build-and-deploy-to-dockerhub:
    if: github.event.workflow_run.conclusion == 'success'
    name: Push verified image to dockerhub
    needs: create-variables
    runs-on: ubuntu-latest
    env:
      CLOUD_CONFIG_VERSION: ${{ needs.create-variables.outputs.cloud-config-version }}
      CLOUD_CONFIG_VERSION_SHORT: ${{ needs.create-variables.outputs.cloud-config-version-short }}
      JAVA: ${{ matrix.jvmType }}${{ matrix.jvmVersion }}
      JVM_TYPE: ${{ matrix.jvmVersion }}
      JVM_VERSION: ${{ matrix.jvmVersion }}
      SHORT_SHA: ${{ needs.create-variables.outputs.short-sha }}
    strategy:
      matrix:
        jvmType: [jre, jdk]
        jvmVersion: [8, 11, 17]
        exclude:
          - jvmVersion: 17
            jvmType: jre
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push java ${{ matrix.jvmVersion }} ${{ matrix.jvmType }} docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_VERSION=${{ matrix.jvmVersion }}
            JVM_TYPE=${{ matrix.jvmType }}
          context: .
          platforms: ${{ env.PLATFORMS }}
          no-cache: true
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-${{ env.JAVA }},
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.JAVA }},
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-${{ env.JAVA }},
      - name: Build and push java ${{ matrix.jvmVersion }} ${{ matrix.jvmType }} default docker image
        if: github.event.workflow_run.head_branch == 'main' && matrix.jvmVersion == '11'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_VERSION=${{ matrix.jvmVersion }}
            JVM_TYPE=${{ matrix.jvmType }}
          context: .
          platforms: ${{ env.PLATFORMS }}
          no-cache: true
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.JAVA }}
      - name: Build and push latest docker image
        if: github.event.workflow_run.head_branch == 'main' && matrix.jvmVersion == '11' && matrix.jvmType == 'jre'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_VERSION=${{ matrix.jvmVersion }}
            JVM_TYPE=${{ matrix.jvmType }}
          context: .
          platforms: ${{ env.PLATFORMS }}
          no-cache: true
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
