name: dockerhub deploy

on:
  workflow_run:
    workflows: ['CI']
    branches: [main, '[2-9].[0-9]']
    types:
      - completed

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    name: Push verified image to dockerhub

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set cloud config versions in github env
        run: |
          SEMVER=$(./gradlew dependencyInsight --dependency org.springframework.cloud:spring-cloud-config-server | grep 'org.springframework.cloud:spring-cloud-config-server:' | tail -1 | cut -d ':' -f 3-)
          SEMVER_MINOR=$(echo $SEMVER | cut -d. -f1,2)
          echo "CLOUD_CONFIG_VERSION=$SEMVER" >> $GITHUB_ENV
          echo "CLOUD_CONFIG_VERSION_SHORT=$SEMVER_MINOR" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push java 8 JRE
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=1.8
            JVM_TAG=8-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jre8
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jre8
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jre8

      - name: Tag and push java 8 JRE default image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=1.8
            JVM_TAG=8-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: |
            ${{ github.repository }}:jre8

      - name: Build and push java 8 JDK
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=1.8
            JVM_TAG=8-jdk-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jdk8
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk8
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk8

      - name: Tag and push java 8 JDK default image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=1.8
            JVM_TAG=8-jdk-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: |
            ${{ github.repository }}:jdk8

      - name: Build and push java 11 JRE
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jre11
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jre11
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jre11

      - name: Tag and push java 11 JRE default images
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:jre11

      - name: Build and push java 11 JDK
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
            JVM_TAG=11-jdk-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jdk11
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk11
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk11

      - name: Tag and push java 11 JDK default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
            JVM_TAG=11-jdk-focal
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ github.repository }}:jdk11

      - name: Build and push java 17 JRE
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          build-args: |
            JVM_TARGET=17
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jre17
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jre17
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jre17

      - name: Tag and push java 17 JRE default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          build-args: |
            JVM_TARGET=17
          push: true
          tags: |
            ${{ github.repository }}:jre17

      - name: Build and push java 17 JDK
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          build-args: |
            JVM_TARGET=17
            JVM_TAG=17-jdk-focal
          no-cache: true
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-${{ env.SHORT_SHA }}-jdk17
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk17
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk17

      - name: Tag and push java 17 JDK default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          build-args: |
            JVM_TARGET=17
            JVM_TAG=17-jdk-focal
          push: true
          tags: |
            ${{ github.repository }}:jdk17