name: dockerhub deploy

on:
  workflow_run:
    workflows: ['CI']
    branches: [main, '[2-9].[0-9]']
    types:
      - completed

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    name: Push verified image to dockerhub

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set cloud config versions in github env
        run: |
          SEMVER=$(./gradlew dependencyInsight --dependency org.springframework.cloud:spring-cloud-config-server | grep 'org.springframework.cloud:spring-cloud-config-server:' | tail -1 | cut -d ':' -f 3-)
          SEMVER_MINOR=$(echo $SEMVER | cut -d. -f1,2)
          echo "CLOUD_CONFIG_VERSION=$SEMVER" >> $GITHUB_ENV
          echo "CLOUD_CONFIG_VERSION_SHORT=$SEMVER_MINOR" >> $GITHUB_ENV

      - name: Build and push java 8
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=8
          context: .
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk8
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk8

      - name: Tag and push java 8 default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=8
          context: .
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:jdk8

      - name: Build and push java 11
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
          context: .
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk11
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk11

      - name: Tag and push java 11 default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            JVM_TARGET=11
          context: .
          push: true
          tags: |
            ${{ github.repository }}:jdk11

      - name: Build and push java 15
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            JVM_TARGET=15
          push: true
          tags: |
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION }}-jdk15
            ${{ github.repository }}:${{ env.CLOUD_CONFIG_VERSION_SHORT }}-jdk15

      - name: Tag and push java 15 default image
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            JVM_TARGET=15
          push: true
          tags: |
            ${{ github.repository }}:jdk15